# Decap CMS Configuration File

# The backend option specifies how to access the content for your site
backend:
  name: github
  repo: bosinic-tech-78/cronache-di-krynn  
  branch: master
  auth_endpoint: https://decap-oauth-provider.netlify.app/auth

# Uncomment below to enable drafts https://www.decapcms.org/docs/add-to-your-site/#editorial-workflow
# publish_mode: editorial_workflow

# Uncomment below to enable a link to your published site in the header bar of Decap CMS
# site_url: https://eleventy-netlify-boilerplate.netlify.app/

media_folder: "static/img" # Media files will be stored in the repo under images/uploads

collections:
  - name: "diario"
    label: "Diario di Campagna"
    folder: "src/diario"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titolo Capitolo", name: "title", widget: "string"}
      - {label: "Data Sessione", name: "date", widget: "datetime"}
      - {label: "Immagine di Copertina", name: "image", widget: "image", required: false}
      - {label: "Riassunto degli Eventi", name: "body", widget: "markdown"}

  - name: "personaggi"
    label: "Dramatis Personae"
    folder: "src/personaggi" 
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nome Personaggio", name: "title", widget: "string"}
      - {label: "Tipo", name: "tipo", widget: "select", options: ["Giocatore (PC)", "Personaggio Non Giocante (PNG)"]}
      - {label: "Razza e Classe", name: "razza_classe", widget: "string"}
      - {label: "Classe Armatura (CA)", name: "ca", widget: "number", value_type: "int", required: false}
      - {label: "Punti Ferita (PF)", name: "pf", widget: "number", value_type: "int", required: false}
      - {label: "Ritratto", name: "image", widget: "image", required: false}
      - {label: "Storia e Appunti", name: "body", widget: "markdown"}
  - name: "mappe"
    label: "Atlante & Mappe"
    folder: "src/mappe"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titolo Luogo / Mappa", name: "title", widget: "string" }
      - { label: "Descrizione Breve", name: "description", widget: "string" }
      - { label: "Immagine Mappa", name: "image", widget: "image", required: false }
      - { label: "Note Geografiche / Dettagli", name: "body", widget: "markdown", required: false }
